---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: default
  labels:
    app: account-deployment
spec:
  selector:
    matchLabels:
      app: account-deployment
  template:
    metadata:
      labels:
        app: account-deployment
    spec:
      containers:
        - name: account-service
          image: europe-west10-docker.pkg.dev/profile-system-428115/profile-system-repository/account.service:1.1-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=profile&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: default
  labels:
    app: account-service
spec:
  selector:
    app: account-deployment
  ports:
    - name: account-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  namespace: default
  labels:
    app: profile-deployment
spec:
  selector:
    matchLabels:
      app: profile-deployment
  template:
    metadata:
      labels:
        app: profile-deployment
    spec:
      containers:
        - name: profile-service
          image: europe-west10-docker.pkg.dev/profile-system-428115/profile-system-repository/profile.service:1.1-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=profile&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: default
  labels:
    app: profile-service
spec:
  selector:
    app: profile-deployment
  ports:
    - name: profile-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: ""